receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 5s
    timeout: 5s
    api_version: "1.45"

processors:
  batch:

exporters:
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/v1/metrics
    traces_endpoint: http://victoriatraces:10428/opentelemetry/v1/traces
    tls:
      insecure: true

extensions:
  health_check:

service:
  extensions: [ health_check ]
  pipelines:
    metrics:
      receivers: [ otlp, docker_stats ]
      processors: [ batch ]
      exporters: [ otlphttp/victoriametrics ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp/victoriametrics ]