receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 5s
    timeout: 5s
    api_version: "1.45"

processors:
  batch:

exporters:
  otlphttp/victoriametrics:
    compression: gzip
    encoding: proto
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/v1/metrics
    traces_endpoint: http://victoriatraces:10428/insert/opentelemetry/v1/traces
    tls:
      insecure: true

connectors:
  spanmetrics:
    dimensions:
      - name: http.route
    histogram:
      explicit:
        buckets: [0.05s, 0.1s, 0.25s, 0.5s, 1s, 2.5s, 5s, 10s, 15s]

extensions:
  health_check:

service:
  extensions: [ health_check ]
  pipelines:
    metrics:
      receivers: [ otlp, docker_stats, spanmetrics ]
      processors: [ batch ]
      exporters: [ otlphttp/victoriametrics ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlphttp/victoriametrics, spanmetrics ]